# Generated by Django 5.0.6 on 2024-07-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('author_name', models.CharField(max_length=50, null=True)),
                ('publish_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
